CREATE OR REPLACE PROCEDURE `ds_b_sp_core.adquisiciones_productos_observadas_calificacion`(val_first_day DATE, val_last_day DATE, PROJECT_ID_PLT STRING, PROJECT_ID_ORO STRING)
OPTIONS (strict_mode=false)
BEGIN
EXECUTE IMMEDIATE CONCAT(

"INSERT INTO " ,PROJECT_ID_ORO, ".`ds_oro_generico.t_b_ant_adquisiciones_productos_observadas` (",
      "cliente_id,",
      "target_tdc_umbral,",
      "target_hipo_umbral,",
      "target_auto_umbral,",
      "target_cn_umbral,",
      "target_fondos_umbral,",
      "prediccion_tdc_umbral,",
      "prediccion_hipo_umbral,",
      "prediccion_auto_umbral,",
      "prediccion_cn_umbral,",
      "prediccion_fondos_umbral",
      " )",
  " SELECT",
  " b.cliente_id,",
  "CASE WHEN 'TDC' IN UNNEST (arreglo) THEN 1 ELSE 0 END,",
  "CASE WHEN 'HIPO' IN UNNEST(arreglo) THEN 1 ELSE 0 END,",
  "CASE WHEN 'AUTO' IN UNNEST(arreglo) THEN 1 ELSE 0 END,",
  "CASE WHEN 'CN' IN UNNEST(arreglo) THEN 1 ELSE 0 END,",
  "CASE WHEN 'FONDOS' IN UNNEST(arreglo) THEN 1 ELSE 0 END,",
  "b.prediccion_tdc_umbral,",
  "b.prediccion_hipo_umbral,",
  "b.prediccion_auto_umbral,",
  "b.prediccion_cn_umbral,",
  "b.prediccion_fondos_umbral ",
" FROM ( ( ",
   " SELECT ",
     " cliente_id,",
      "arreglo",
   " FROM ( ",
     " SELECT ",
       " cliente_id,",
        "arreglo,",
        "ROW_NUMBER() OVER (PARTITION BY cliente_id) AS row_num_2 ",
     " FROM ( ",
       " SELECT ",
         " *,",
          "ROW_NUMBER() OVER (PARTITION BY cliente_id, producto_tipo ORDER BY fecha_informacion DESC ) AS row_num,",
          "ARRAY_AGG(producto_tipo) OVER(PARTITION BY cliente_id) AS arreglo ",
       " FROM ", PROJECT_ID_PLT, ".`ds_b_ant_plt.t_b_ant_adquisiciones_productos_observadas`",
       "WHERE fecha_informacion BETWEEN '",val_first_day,"' AND ", "DATE_ADD('",val_last_day,"',INTERVAL -1 MONTH)) ",
      " WHERE row_num=1 ) ",
   " WHERE row_num_2=1 ) a ",
  " RIGHT JOIN ( ",
   " SELECT ",
    " * ",
    " FROM ", PROJECT_ID_ORO, ".`.ds_b_ant_oro.t_b_ant_calif_prop_prod_hist_vxx`",
    "WHERE fecha_informacion BETWEEN '",val_first_day,"' AND ", "LAST_DAY('",val_last_day,"'))b ",
 " ON a.cliente_id=b.cliente_id) "
 );
END;