CREATE OR REPLACE PROCEDURE `ds_b_sp_core.insumos_abandono_hipoteca_hist_plata`(val_first_day DATE, val_last_day DATE, PROJECT_ID_BRC STRING, PROJECT_ID_PLT STRING)
OPTIONS (strict_mode=false)
BEGIN
  EXECUTE IMMEDIATE CONCAT (
     "INSERT INTO ",PROJECT_ID_PLT, ".`ds_b_ant_plt.t_b_ant_ins_abn_hip_hist_vxx`(",
    "credito_numero,",
    "mes_fecha,",
    "plazo_total_credito_meses_numero,",
    "credito_monto,",
    "garantia_monto,",
    "tasa_cobrada_pct,",
    "contable_ultimo_balance_saldo,",
    "modalidad_credito_cve,",
    "ingreso_tipo,",
    "broker_nombre,",
    "broker_bandera,",
    "antig_credito_meses_numero,",
    "pago_exigible_monto,",
    "pago_monto,",
    "plazo_remanente_credito_numero,",
    "aforo_monto,",
    "nivel_riesgo_cliente_tipo,",
    "prom_voluntad_pago_7m_monto,",
    "cliente_id,",
    "consultas_buro_1m_numero,",
    "consultas_buro_3m_numero,",
    "consultas_buro_6m_numero,",
    "consultas_buro_12m_numero,",
    "max_num_pagos_vencidos_numero,",
    "pct_ltv_monto,",
    "pct_ltv_cierre_monto,",
    "score_riesgo_numero",
    ")",
    "SELECT ",
    "CAST(credito as INT64) credito,",
    "mth,",
    "plazo,",
    "impcred,",
    "impgaranti,",
    "tasacobrad,",
    "n_saldocontable,",
    "modalidad,",
    "tipo_ingreso,",
    "broker,",
    "f_broker,",
    "mob,",
    "exigible,",
    "pago,",
    "n_plazo_remanente,",
    "n_ltv,",
    "nivel_riesgo,",
    "prom_vpago,",
    "CAST(sic as INT64) sic,",
    "consulta_1m,",
    "consulta_3m,",
    "consulta_6m,",
    "consulta_12m,",
    "max_npv,",
    "ltv,",
    "ltv_cierre,",
    "n_score_riesgo ",
    "FROM ", PROJECT_ID_BRC,".`ds_b_ant_brc.insumos_abandono_hipoteca_hist`",
    "WHERE mth BETWEEN '",val_first_day, "' AND ", "'",val_last_day, "'"
  );
  END;